[package]
name = "criterion_compare"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
flexstr = { version = "0.7", features = ["serde"] }
indexmap = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
